short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 8
patch = 0
status = "dev"
module_config = ""
website = "https://blazium.app"
docs = "latest"
external_major = 0
external_minor = 6
external_patch = 0
external_status = "dev"
external_sha = ""
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
