short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 5
patch = 0
status = "stable"
module_config = ""
website = "https://blazium.app"
docs = "latest"
external_major = 0
external_minor = 8
external_patch = 0
external_status = "dev"
external_sha = "876b290332ec6f2e6d173d08162a02aa7e6ca46d"
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
blazium_xor_key = ""
