#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.tests_sources = []

env_tests = env.Clone()

if env["module_luau_module_enabled"]:
    luau_thirdparty = "#thirdparty/luau/"
    env_tests.Append(
        CPPPATH=[
            "#modules/luau_module",
            luau_thirdparty + "Common/include",
            luau_thirdparty + "Ast/include",
            luau_thirdparty + "Compiler/include",
            luau_thirdparty + "VM/include",
            luau_thirdparty + "VM/src",
        ]
    )

# We must disable the THREAD_LOCAL entirely in doctest to prevent crashes on debugging
# Since we link with /MT thread_local is always expired when the header is used
# So the debugger crashes the engine and it causes weird errors
# Explained in https://github.com/onqtam/doctest/issues/401
if env_tests["platform"] == "windows":
    env_tests.Append(CPPDEFINES=[("DOCTEST_THREAD_LOCAL", "")])

if env["disable_exceptions"]:
    env_tests.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env_tests.add_source_files(env.tests_sources, "*.cpp")

lib = env_tests.add_library("tests", env.tests_sources)
env.Prepend(LIBS=[lib])
