#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_assettags = env_modules.Clone()

env_assettags.add_source_files(env.modules_sources, "*.cpp")
env_assettags.add_source_files(env.modules_sources, "editor/*.cpp")
env_assettags.add_source_files(env.modules_sources, "persistence/*.cpp")

if env["tests"]:
    env_assettags.Append(CPPDEFINES=["TESTS_ENABLED"])

    if env["disable_exceptions"]:
        env_assettags.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])
