#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_analytics = env_modules.Clone()

env_analytics.add_source_files(env.modules_sources, "register_types.cpp")
env_analytics.add_source_files(env.modules_sources, "analytics.cpp")
env_analytics.add_source_files(env.modules_sources, "analytics_project_settings.cpp")
env_analytics.add_source_files(env.modules_sources, "analytics_http.cpp")
env_analytics.add_source_files(env.modules_sources, "analytics_queue.cpp")

if env.editor_build:
    env_analytics.add_source_files(env.modules_sources, "analytics_editor_export_plugin.cpp")

if env["tests"]:
    env_analytics.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_analytics.add_source_files(env.modules_sources, "tests/test_analytics.cpp")
    if env["disable_exceptions"]:
        env_analytics.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])
