#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_justamcp = env_modules.Clone()

# Blazium source files
env_justamcp.add_source_files(env.modules_sources, "*.cpp")
env_justamcp.add_source_files(env.modules_sources, "tools/*.cpp")
env_justamcp.add_source_files(env.modules_sources, "tools/prompts/*.cpp")
env_justamcp.add_source_files(env.modules_sources, "tools/resources/*.cpp")

if env["tests"]:
    env_justamcp.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_justamcp.add_source_files(env.modules_sources, "tests/test_justamcp_elicitation.cpp")
    env_justamcp.add_source_files(env.modules_sources, "tests/test_justamcp_oauth_discovery.cpp")
    env_justamcp.add_source_files(env.modules_sources, "tests/test_justamcp_protocol_matrix.cpp")

    if env["disable_exceptions"]:
        env_justamcp.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

# Editor only sources can be separated if needed, but since we use `#ifdef TOOLS_ENABLED` inline or in `register_types.cpp`
# this is usually sufficient.
