#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import default_theme_builders

# Compile both the Godot 4.8 default theme (extra controls / fill_default_theme)
# and the always-on Blazium runtime theme used by ThemeDB.
sources = [
    "theme_db.cpp",
    "theme_owner.cpp",
    "default_theme.cpp",
    "blazium_default_theme.cpp",
]
env.add_source_files(env.scene_sources, sources)

SConscript("icons/SCsub")

env.CommandNoCache(
    "#scene/theme/default_font.gen.h",
    "#thirdparty/fonts/OpenSans_SemiBold.woff2",
    env.Run(default_theme_builders.make_fonts_header),
)
