#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gif = env_modules.Clone()

thirdparty_obj = []
thirdparty_dir = "#thirdparty/cgif/"
thirdparty_sources = [
    "src/cgif.c",
    "src/cgif_raw.c",
    "src/cgif_rgb.c",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_gif.Prepend(CPPPATH=[thirdparty_dir + "inc"])

env_thirdparty = env_gif.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

module_obj = []
env_gif.add_source_files(module_obj, "*.cpp")

if env.editor_build:
    env_gif.add_source_files(module_obj, "editor/*.cpp")

if env["tests"]:
    env_gif.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gif.add_source_files(module_obj, "tests/test_gif.cpp")
    if env["disable_exceptions"]:
        env_gif.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env.modules_sources += module_obj
env.Depends(module_obj, thirdparty_obj)
