#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_twitchapi = env_modules.Clone()

# Blazium source files
env_twitchapi.add_source_files(env.modules_sources, "*.cpp")
env_twitchapi.add_source_files(env.modules_sources, "requests/*.cpp")
