#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_inter_dvd = env_modules.Clone()

env_inter_dvd.add_source_files(env.modules_sources, "*.cpp")
env_inter_dvd.add_source_files(env.modules_sources, "machine/*.cpp")
env_inter_dvd.add_source_files(env.modules_sources, "author/*.cpp")
env_inter_dvd.add_source_files(env.modules_sources, "editor/*.cpp")
env_inter_dvd.add_source_files(env.modules_sources, "editor/export/*.cpp")

if env["tests"]:
    env_inter_dvd.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_inter_dvd.add_source_files(env.modules_sources, "tests/*.cpp")
    if env["disable_exceptions"]:
        env_inter_dvd.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])
