#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_device_autorun = env_modules.Clone()

env_device_autorun.add_source_files(env.modules_sources, "*.cpp")
env_device_autorun.add_source_files(env.modules_sources, "editor/*.cpp")

if env["tests"]:
    env_device_autorun.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_device_autorun.add_source_files(env.modules_sources, "tests/*.cpp")
    if env["disable_exceptions"]:
        env_device_autorun.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])
