#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_navimesh_export = env_modules.Clone()

if env.editor_build:
    env_navimesh_export.add_source_files(env.modules_sources, "*.cpp")
    env_navimesh_export.add_source_files(env.modules_sources, "editor/*.cpp")

if env["tests"]:
    env_navimesh_export.Append(CPPDEFINES=["TESTS_ENABLED"])
    if env["disable_exceptions"]:
        env_navimesh_export.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])
