#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

# Godot 4.8 split ScriptLanguage editor APIs into EditorLanguage and changed
# Script/RefCounted memnew contracts. Compile a stub until Luau is rewritten.
env_luau_module = env_modules.Clone()
module_obj = []
env_luau_module.add_source_files(module_obj, "register_types.cpp")
env.modules_sources += module_obj
