#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_trenchbroom = env_modules.Clone()

module_obj = []
env_trenchbroom.add_source_files(module_obj, "*.cpp")
env_trenchbroom.add_source_files(module_obj, "core/*.cpp")
env_trenchbroom.add_source_files(module_obj, "util/*.cpp")
env_trenchbroom.add_source_files(module_obj, "fgd/*.cpp")
env_trenchbroom.add_source_files(module_obj, "trenchbroom/*.cpp")
env_trenchbroom.add_source_files(module_obj, "import/quake_map_file.cpp")
env_trenchbroom.add_source_files(module_obj, "import/quake_palette_file.cpp")
env_trenchbroom.add_source_files(module_obj, "import/quake_wad_file.cpp")

if env.editor_build:
    env_trenchbroom.add_source_files(module_obj, "import/resource_importer_map.cpp")
    env_trenchbroom.add_source_files(module_obj, "import/resource_importer_palette.cpp")
    env_trenchbroom.add_source_files(module_obj, "import/resource_importer_wad.cpp")
    env_trenchbroom.add_source_files(module_obj, "import/resource_importer_wal.cpp")
    env_trenchbroom.add_source_files(module_obj, "editor/*.cpp")

env_trenchbroom.add_source_files(module_obj, "netradiant/*.cpp")

if env["tests"]:
    env_trenchbroom.add_source_files(module_obj, "tests/*.cpp")

env.modules_sources += module_obj
