#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_obfuscation = env_modules.Clone()
env_obfuscation.Prepend(CPPPATH=["#modules/obfuscation"])

module_obj = []
env_obfuscation.add_source_files(module_obj, "*.cpp")
env_obfuscation.add_source_files(module_obj, "codec/*.cpp")
env_obfuscation.add_source_files(module_obj, "stego/*.cpp")
env_obfuscation.add_source_files(module_obj, "seeds/*.cpp")
env_obfuscation.add_source_files(module_obj, "io/*.cpp")

if env.editor_build:
    env_obfuscation.add_source_files(module_obj, "editor/*.cpp")

if env["tests"]:
    env_obfuscation.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_obfuscation.add_source_files(module_obj, "tests/test_obfuscation.cpp")
    if env["disable_exceptions"]:
        env_obfuscation.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env.modules_sources += module_obj
