#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_screensaver = env_modules.Clone()

env_screensaver.add_source_files(env.modules_sources, "register_types.cpp")
env_screensaver.add_source_files(env.modules_sources, "screensaver_cmdline.cpp")
env_screensaver.add_source_files(env.modules_sources, "screensaver_password.cpp")
env_screensaver.add_source_files(env.modules_sources, "screensaver.cpp")

if env.editor_build:
    env_screensaver.add_source_files(env.modules_sources, "editor/*.cpp")
    env_screensaver.add_source_files(env.modules_sources, "editor/export/*.cpp")

if env["tests"]:
    env_screensaver.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_screensaver.add_source_files(env.modules_sources, "tests/*.cpp")
    if env["disable_exceptions"]:
        env_screensaver.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])
