#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_discord_module = env_modules.Clone()
env_discord_module.add_source_files(env.modules_sources, "*.cpp")
