#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_anticheat = env_modules.Clone()

env_anticheat.add_source_files(env.modules_sources, "*.cpp")
env_anticheat.add_source_files(env.modules_sources, "tweetnacl.c")

if env.editor_build:
    env_anticheat.add_source_files(env.modules_sources, "editor/*.cpp")
