#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gew = env_modules.Clone()
env_gew.Prepend(CPPPATH=["#thirdparty/enet"])

module_obj = []
env_gew.add_source_files(module_obj, "*.cpp")

if env["tests"]:
    env_gew.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gew.add_source_files(module_obj, "tests/test_games_enet_webrtc.cpp")
    if env["disable_exceptions"]:
        env_gew.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env.modules_sources += module_obj
